# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               David Brait
tagline:             "Topics in Data Science"
description:         'A blog that explores interesting data '
url:                 http://dbrait.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              David Brait
  url:               https://twitter.com/dbrait
  email:             david.brait@gmail.com

# Custom vars

